# Generated by Django 3.0.5 on 2020-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCircuit',
            fields=[
                ('vcid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('NP', 'Interface H/W Not Present'), ('EI', 'Encapsulation Invalid'), ('EM', 'Encapsulation Mismatch'), ('VM', 'VLAN ID Mismatch'), ('BK', 'Backup Connection'), ('ST', 'Standby Connection'), ('LD', 'Local Site Signaled Down'), ('HS', 'Hot-standby Connection')], max_length=2)),
                ('context', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['vcid'],
            },
        ),
    ]
