# Generated by Django 3.0.6 on 2020-07-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_virtual_circuit_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualcircuit',
            options={'ordering': ['vcid'], 'verbose_name': 'Virtual Circuit', 'verbose_name_plural': 'Virtual Circuits'},
        ),
        migrations.AlterModelOptions(
            name='virtualcircuitvlan',
            options={'ordering': ['virtual_circuit'], 'verbose_name': 'Virtual-Circuit-to-VLAN connection', 'verbose_name_plural': 'Virtual-Circuit-to-VLAN connections'},
        ),
    ]
