# Generated by Django 3.1 on 2020-10-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0037_ipaddress_assignment'),
        ('netbox_virtual_circuit_plugin', '0004_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcircuitvlan',
            name='vlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_circuit', to='ipam.vlan'),
        ),
    ]
