# Generated by Django 3.1 on 2020-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_virtual_circuit_plugin', '0005_vlan_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcircuit',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
